export const PROMOTIONAL_TAGS = [
    { name: "Modern Technologies" },
    { name: "Future Online" },
    { name: "Unmatched Performance" },
    { name: "Speed" },
    { name: "Dynamic Content" },
    { name: "Responsiveness" },
    { name: "Lightning Fast" },
    { name: "New Generation" },
    { name: "Intuitive Interface" },
    { name: "Scalability" },
    { name: "Security" },
    { name: "Integration" },
    { name: "Professionalism" },
    { name: "Personalized Approach" },
    { name: "Mobility" },
];
