import type { Metadata } from "next";
import "./globals.css";

import Nav from "@/components/Header/Nav";
import Footer from "@/components/Footer/Footer";
import { roboto } from "@/fonts";
import Background from "@/components/Background";

export const metadata: Metadata = {
    title: "Seovileo",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${roboto.className} bg-background-primary flex flex-col min-h-screen text-foreground-secondary w-full overflow-x-hidden`}
            >
                <Nav />
                <Background />
                <main className="flex-1">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
